apiVersion: v1
kind: Secret
metadata:
  name: host-certificate
  namespace: {{ .Values.deployment.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.config.certificates.host.crt }} 
  tls.key: {{ .Values.config.certificates.host.key }}
