apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storm-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storm-webdav
            port:
              number: 8085
  ingressClassName: nginx

