apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: storm-webdav
  name: storm-webdav
  namespace: {{ .Values.deployment.namespace }}
spec:
  type: NodePort
  ports:
  - name: "8443"
    port: 8443
    targetPort: 8443
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    io.kompose.service: storm-webdav
status:
  loadBalancer: {}
