apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storm-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.proxyBodySize }}
    nginx.ingress.kubernetes.io/proxy-buffering: {{ .Values.proxyBuffering }}
    nginx.ingress.kubernetes.io/proxy-request-buffering: {{ .Values.proxyRequestBuffering}}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storm-webdav
            port:
              number: 8085
  ingressClassName: nginx

