# Trusted OAuth/OIDC token issuers
# Note that this list only define the issuers recognized by this storm-webdav
# instance.
#
# In order to enable an OAuth token issuer in the context of a storage area, such
# issuer must be included in the list of trusted issuer specified in this file
# __and__ in the list of trusted organizations for the storage area in the storage area
# properties in /etc/storm/webdav/sa.d.
#
# Example:
#
# To trust the iam-test.indigo-datacloud.eu organization for the storage area
# example, this must be list among the trusted OAuth token issuers, in
# `/etc/storm/webdav/config/application.yml:`
#
# oauth:
#   issuers:
#     - name: iam-test
#       issuer: https://iam-test.indigo-datacloud.eu/
#
# And in the storage area configuration `/etc/storm/sa.d/example.properties`:
#
# ...
# orgs=https://iam-test.indigo-datacloud.eu
#
oauth:
  enable-oidc: true
  issuers:
    - name: escape
      issuer: https://iam-escape.cloud.cnaf.infn.it/
    - name: ska
      issuer: https://ska-iam.stfc.ac.uk/
spring:
  security:
    oauth2:
      client:
        provider:
          escape:
            issuer-uri: https://iam-escape.cloud.cnaf.infn.it/
          ska:
            issuer-uri: https://ska-iam.stfc.ac.uk/
        registration:
          escape:
            provider: escape
            client-name:
            client-id:
            client-secret:
            scope:
              - openid
              - profile
              - wlcg.groups